graph TD
	__start__["Başlangıç"]
	reservation_agent["Rezervasyon Ajanı"]
	data_extractor["Veri Çıkarıcı"]
	router["Yönlendirici"]
	fetch_reservations_tool["Rezervasyon Listeleme"] 
	add_reservation_tool["Rezervasyon Ekleme"]
	update_reservation_tool["Rezervasyon Güncelleme"]
	delete_reservation_tool["Rezervasyon Silme"]
	check_availability_tool["Müsaitlik Kontrolü"]
	end_node["Bitiş"]
	__end__["Son"]
	
	__start__ --> reservation_agent
	add_reservation_tool --> end_node
	check_availability_tool --> reservation_agent
	data_extractor --> router
	delete_reservation_tool --> reservation_agent
	end_node --> __end__
	fetch_reservations_tool --> end_node
	update_reservation_tool --> reservation_agent
	
	reservation_agent -. Analiz Et .-> data_extractor
	reservation_agent -. Sonlandır .-> end_node
	router -. Listele .-> fetch_reservations_tool
	router -. Ekle .-> add_reservation_tool
	router -. Güncelle .-> update_reservation_tool
	router -. Sil .-> delete_reservation_tool
	router -. Kontrol Et .-> check_availability_tool
	router -. Sonlandır .-> end_node

    style __start__ fill:#58c4dc,stroke:#333,stroke-width:1px
    style __end__ fill:#ff9e9e,stroke:#333,stroke-width:1px
    style end_node fill:#ff9e9e,stroke:#333,stroke-width:1px
    style reservation_agent fill:#f2f0ff,stroke:#333,stroke-width:1px
    style data_extractor fill:#f2f0ff,stroke:#333,stroke-width:1px
    style router fill:#f2f0ff,stroke:#333,stroke-width:1px
    style fetch_reservations_tool fill:#f2f0ff,stroke:#333,stroke-width:1px
    style add_reservation_tool fill:#f2f0ff,stroke:#333,stroke-width:1px
    style update_reservation_tool fill:#f2f0ff,stroke:#333,stroke-width:1px
    style delete_reservation_tool fill:#f2f0ff,stroke:#333,stroke-width:1px
    style check_availability_tool fill:#f2f0ff,stroke:#333,stroke-width:1px 